import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Cada sidebar es independiente: al entrar en Novedades no se mezclan
 * los códigos SUNAT, y al revés.
 *
 * Las categorías internas salen de las carpetas + `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  novedadesSidebar: [
    {type: 'autogenerated', dirName: 'novedades'},
  ],
  sunatSidebar: [
    {type: 'autogenerated', dirName: 'sunat-errores'},
  ],
};

export default sidebars;
